[2024-03-07T16:21:22.146+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: example_5_solid.fetch_data_task manual__2024-03-07T16:21:19.871923+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
