[2024-03-30T17:26:57.451+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: study_case_etl_all_pipeline.bash_task_2 manual__2024-03-30T17:26:23.531730+00:00 [queued]>
[2024-03-30T17:26:57.459+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: study_case_etl_all_pipeline.bash_task_2 manual__2024-03-30T17:26:23.531730+00:00 [queued]>
[2024-03-30T17:26:57.459+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T17:26:57.471+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): bash_task_2> on 2024-03-30 17:26:23.531730+00:00
[2024-03-30T17:26:57.476+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-03-30T17:26:57.479+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'study_case_etl_all_pipeline', 'bash_task_2', 'manual__2024-03-30T17:26:23.531730+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/running_dbt_core/study_case_etl_all_pipeline.py', '--cfg-path', '/tmp/tmp1u46d58d']
[2024-03-30T17:26:57.481+0000] {standard_task_runner.py:88} INFO - Job 111: Subtask bash_task_2
[2024-03-30T17:26:57.519+0000] {task_command.py:423} INFO - Running <TaskInstance: study_case_etl_all_pipeline.bash_task_2 manual__2024-03-30T17:26:23.531730+00:00 [running]> on host f5156ab87ac1
[2024-03-30T17:26:57.580+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Agus mahari' AIRFLOW_CTX_DAG_ID='study_case_etl_all_pipeline' AIRFLOW_CTX_TASK_ID='bash_task_2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T17:26:23.531730+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-30T17:26:23.531730+00:00'
[2024-03-30T17:26:57.582+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-30T17:26:57.582+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt/credit_card_dwh && dbt run --profiles-dir .']
[2024-03-30T17:26:57.591+0000] {subprocess.py:86} INFO - Output:
[2024-03-30T17:27:00.162+0000] {subprocess.py:93} INFO - [0m17:27:00  Running with dbt=1.7.11
[2024-03-30T17:27:01.263+0000] {subprocess.py:93} INFO - [0m17:27:01  Registered adapter: bigquery=1.7.7
[2024-03-30T17:27:01.322+0000] {subprocess.py:93} INFO - [0m17:27:01  Unable to do partial parsing because of a version mismatch
[2024-03-30T17:27:03.456+0000] {subprocess.py:93} INFO - [0m17:27:03  Encountered an error:
[2024-03-30T17:27:03.456+0000] {subprocess.py:93} INFO - Compilation Error
[2024-03-30T17:27:03.457+0000] {subprocess.py:93} INFO -   Model 'model.credit_card_dwh.stg__credit_card' (models/staging/stg__credit_card.sql) depends on a source named 'agusmahari_data_lake.raw_credit_card' which was not found
[2024-03-30T17:27:05.914+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-03-30T17:27:05.922+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-03-30T17:27:05.925+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=study_case_etl_all_pipeline, task_id=bash_task_2, execution_date=20240330T172623, start_date=20240330T172657, end_date=20240330T172705
[2024-03-30T17:27:05.936+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 111 for task bash_task_2 (Bash command failed. The command returned a non-zero exit code 2.; 96)
[2024-03-30T17:27:05.983+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-30T17:27:06.001+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
