[2024-03-30T16:06:40.652+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: study_case_etl_all_pipeline.bash_task_1 manual__2024-03-30T16:06:04.158800+00:00 [queued]>
[2024-03-30T16:06:40.660+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: study_case_etl_all_pipeline.bash_task_1 manual__2024-03-30T16:06:04.158800+00:00 [queued]>
[2024-03-30T16:06:40.660+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T16:06:40.674+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): bash_task_1> on 2024-03-30 16:06:04.158800+00:00
[2024-03-30T16:06:40.680+0000] {standard_task_runner.py:60} INFO - Started process 6830 to run task
[2024-03-30T16:06:40.684+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'study_case_etl_all_pipeline', 'bash_task_1', 'manual__2024-03-30T16:06:04.158800+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/running_dbt_core/study_case_etl_all_pipeline.py', '--cfg-path', '/tmp/tmpe71dlbok']
[2024-03-30T16:06:40.687+0000] {standard_task_runner.py:88} INFO - Job 45: Subtask bash_task_1
[2024-03-30T16:06:40.725+0000] {task_command.py:423} INFO - Running <TaskInstance: study_case_etl_all_pipeline.bash_task_1 manual__2024-03-30T16:06:04.158800+00:00 [running]> on host 8e1e687a7cdb
[2024-03-30T16:06:40.791+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Agus mahari' AIRFLOW_CTX_DAG_ID='study_case_etl_all_pipeline' AIRFLOW_CTX_TASK_ID='bash_task_1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T16:06:04.158800+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-30T16:06:04.158800+00:00'
[2024-03-30T16:06:40.793+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-30T16:06:40.793+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt/credit_card_dwh && dbt deps && dbt seed --profiles-dir .']
[2024-03-30T16:06:40.803+0000] {subprocess.py:86} INFO - Output:
[2024-03-30T16:06:43.165+0000] {subprocess.py:93} INFO - [0m16:06:43  Running with dbt=1.7.11
[2024-03-30T16:06:45.751+0000] {subprocess.py:93} INFO - [0m16:06:45  Encountered an error:
[2024-03-30T16:06:45.752+0000] {subprocess.py:93} INFO - Version error for package dbt-labs/dbt_utils: Could not find a satisfactory version from options: ['=0.8.0', '>=1.0.0', '<2.0.0']
[2024-03-30T16:06:48.840+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-03-30T16:06:48.848+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-03-30T16:06:48.851+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=study_case_etl_all_pipeline, task_id=bash_task_1, execution_date=20240330T160604, start_date=20240330T160640, end_date=20240330T160648
[2024-03-30T16:06:48.862+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 45 for task bash_task_1 (Bash command failed. The command returned a non-zero exit code 2.; 6830)
[2024-03-30T16:06:48.896+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-30T16:06:48.914+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
