[2024-03-12T08:54:43.318+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_lima_solid.fetch_data_task manual__2024-03-12T08:54:41.373844+00:00 [queued]>
[2024-03-12T08:54:43.327+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_lima_solid.fetch_data_task manual__2024-03-12T08:54:41.373844+00:00 [queued]>
[2024-03-12T08:54:43.327+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-12T08:54:43.337+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): fetch_data_task> on 2024-03-12 08:54:41.373844+00:00
[2024-03-12T08:54:43.342+0000] {standard_task_runner.py:60} INFO - Started process 79 to run task
[2024-03-12T08:54:43.345+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'example_lima_solid', 'fetch_data_task', 'manual__2024-03-12T08:54:41.373844+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/other_ingestion_postgre/main_dag_sql_lima.py', '--cfg-path', '/tmp/tmpt53h8j76']
[2024-03-12T08:54:43.348+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask fetch_data_task
[2024-03-12T08:54:43.395+0000] {task_command.py:423} INFO - Running <TaskInstance: example_lima_solid.fetch_data_task manual__2024-03-12T08:54:41.373844+00:00 [running]> on host 31e68e31498e
[2024-03-12T08:54:43.478+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_lima_solid' AIRFLOW_CTX_TASK_ID='fetch_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T08:54:41.373844+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-12T08:54:41.373844+00:00'
[2024-03-12T08:54:43.481+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-03-12T08:54:44.759+0000] {logging_mixin.py:188} INFO - An error occurred: (mysql.connector.errors.ProgrammingError) 1045 (28000): Access denied for user 'root'@'115.166.127.6' (using password: YES)
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-03-12T08:54:44.760+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-12T08:54:44.768+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=example_lima_solid, task_id=fetch_data_task, execution_date=20240312T085441, start_date=20240312T085443, end_date=20240312T085444
[2024-03-12T08:54:44.794+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-12T08:54:44.811+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
