[2024-03-09T03:56:23.593+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongodb_to_sql8.ingest_csv_to_mysql scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-03-09T03:56:23.603+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongodb_to_sql8.ingest_csv_to_mysql scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-03-09T03:56:23.603+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-09T03:56:23.622+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_csv_to_mysql> on 2024-03-08 00:00:00+00:00
[2024-03-09T03:56:23.627+0000] {standard_task_runner.py:60} INFO - Started process 84 to run task
[2024-03-09T03:56:23.631+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mongodb_to_sql8', 'ingest_csv_to_mysql', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/restrore_mongo/main_dag_sql_delapan.py', '--cfg-path', '/tmp/tmpqj92yax2']
[2024-03-09T03:56:23.635+0000] {standard_task_runner.py:88} INFO - Job 172: Subtask ingest_csv_to_mysql
[2024-03-09T03:56:23.681+0000] {task_command.py:423} INFO - Running <TaskInstance: mongodb_to_sql8.ingest_csv_to_mysql scheduled__2024-03-08T00:00:00+00:00 [running]> on host c9d1ac6dab48
[2024-03-09T03:56:23.768+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mongodb_to_sql8' AIRFLOW_CTX_TASK_ID='ingest_csv_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2024-03-09T03:56:23.770+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-03-09T03:56:26.437+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:26,436 INFO sqlalchemy.engine.Engine SELECT DATABASE()
[2024-03-09T03:56:26.436+0000] {base.py:1863} INFO - SELECT DATABASE()
[2024-03-09T03:56:26.437+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:26,437 INFO sqlalchemy.engine.Engine [raw sql] {}
[2024-03-09T03:56:26.437+0000] {base.py:1868} INFO - [raw sql] {}
[2024-03-09T03:56:27.435+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:27,435 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
[2024-03-09T03:56:27.435+0000] {base.py:1863} INFO - SELECT @@sql_mode
[2024-03-09T03:56:27.436+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:27,436 INFO sqlalchemy.engine.Engine [raw sql] {}
[2024-03-09T03:56:27.436+0000] {base.py:1868} INFO - [raw sql] {}
[2024-03-09T03:56:27.905+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:27,905 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
[2024-03-09T03:56:27.905+0000] {base.py:1863} INFO - SELECT @@lower_case_table_names
[2024-03-09T03:56:27.906+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:27,906 INFO sqlalchemy.engine.Engine [raw sql] {}
[2024-03-09T03:56:27.906+0000] {base.py:1868} INFO - [raw sql] {}
[2024-03-09T03:56:28.356+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:28,355 INFO sqlalchemy.engine.Engine BEGIN (implicit)
[2024-03-09T03:56:28.355+0000] {base.py:1032} INFO - BEGIN (implicit)
[2024-03-09T03:56:28.588+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:28,588 INFO sqlalchemy.engine.Engine SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = %(table_schema)s AND table_name = %(table_name)s
[2024-03-09T03:56:28.588+0000] {base.py:1863} INFO - SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = %(table_schema)s AND table_name = %(table_name)s
[2024-03-09T03:56:28.589+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:28,589 INFO sqlalchemy.engine.Engine [generated in 0.22996s] {'table_schema': 'test', 'table_name': 'transaksi_restore'}
[2024-03-09T03:56:28.589+0000] {base.py:1868} INFO - [generated in 0.22996s] {'table_schema': 'test', 'table_name': 'transaksi_restore'}
[2024-03-09T03:56:29.050+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:29,050 INFO sqlalchemy.engine.Engine SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = %(table_schema)s AND table_name = %(table_name)s
[2024-03-09T03:56:29.050+0000] {base.py:1863} INFO - SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = %(table_schema)s AND table_name = %(table_name)s
[2024-03-09T03:56:29.051+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:29,050 INFO sqlalchemy.engine.Engine [cached since 0.6916s ago] {'table_schema': 'test', 'table_name': 'transaksi_restore'}
[2024-03-09T03:56:29.050+0000] {base.py:1868} INFO - [cached since 0.6916s ago] {'table_schema': 'test', 'table_name': 'transaksi_restore'}
[2024-03-09T03:56:29.499+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:29,499 INFO sqlalchemy.engine.Engine SHOW FULL TABLES FROM `test`
[2024-03-09T03:56:29.499+0000] {base.py:1863} INFO - SHOW FULL TABLES FROM `test`
[2024-03-09T03:56:29.500+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:29,500 INFO sqlalchemy.engine.Engine [raw sql] {}
[2024-03-09T03:56:29.500+0000] {base.py:1868} INFO - [raw sql] {}
[2024-03-09T03:56:29.962+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:29,961 INFO sqlalchemy.engine.Engine SHOW CREATE TABLE `transaksi_restore`
[2024-03-09T03:56:29.961+0000] {base.py:1863} INFO - SHOW CREATE TABLE `transaksi_restore`
[2024-03-09T03:56:29.962+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:29,962 INFO sqlalchemy.engine.Engine [raw sql] {}
[2024-03-09T03:56:29.962+0000] {base.py:1868} INFO - [raw sql] {}
[2024-03-09T03:56:30.433+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:30,433 INFO sqlalchemy.engine.Engine 
DROP TABLE transaksi_restore
[2024-03-09T03:56:30.433+0000] {base.py:1863} INFO - 
DROP TABLE transaksi_restore
[2024-03-09T03:56:30.434+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:30,433 INFO sqlalchemy.engine.Engine [no key 0.23114s] {}
[2024-03-09T03:56:30.433+0000] {base.py:1868} INFO - [no key 0.23114s] {}
[2024-03-09T03:56:30.660+0000] {logging_mixin.py:188} INFO - 2024-03-09 03:56:30,660 INFO sqlalchemy.engine.Engine COMMIT
[2024-03-09T03:56:30.660+0000] {base.py:1092} INFO - COMMIT
[2024-03-09T03:56:31.116+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 633, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Unknown table 'test.transaksi_restore'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 86, in wrapper
    result = method(cnx, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 641, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1051 (42S02): Unknown table 'test.transaksi_restore'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/restrore_mongo/main_dag_sql_delapan.py", line 117, in ingest_csv_to_mysql
    df.to_sql(name='transaksi_restore', con=engine, if_exists='replace', index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1910, in to_sql
    table = self.prep_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1814, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 907, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1963, in drop_table
    self.get_table(table_name, schema).drop(bind=self.con)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 979, in drop
    bind._run_ddl_visitor(ddl.SchemaDropper, self, checkfirst=checkfirst)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2221, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 1106, in visit_table
    self.connection.execute(DropTable(table))
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 86, in wrapper
    result = method(cnx, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 641, in cmd_query
    raise get_mysql_exception(
sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1051 (42S02): Unknown table 'test.transaksi_restore'
[SQL: 
DROP TABLE transaksi_restore]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-03-09T03:56:31.136+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=mongodb_to_sql8, task_id=ingest_csv_to_mysql, execution_date=20240308T000000, start_date=20240309T035623, end_date=20240309T035631
[2024-03-09T03:56:31.147+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 172 for task ingest_csv_to_mysql ((mysql.connector.errors.ProgrammingError) 1051 (42S02): Unknown table 'test.transaksi_restore'
[SQL: 
DROP TABLE transaksi_restore]
(Background on this error at: https://sqlalche.me/e/14/f405); 84)
[2024-03-09T03:56:31.176+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-09T03:56:31.187+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
