[2024-03-17T04:51:04.645+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: study_case_etl_cloud_storage_dua.format_to_parquet_task manual__2024-03-17T04:50:55.736040+00:00 [queued]>
[2024-03-17T04:51:04.653+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: study_case_etl_cloud_storage_dua.format_to_parquet_task manual__2024-03-17T04:50:55.736040+00:00 [queued]>
[2024-03-17T04:51:04.653+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-17T04:51:04.663+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2024-03-17 04:50:55.736040+00:00
[2024-03-17T04:51:04.668+0000] {standard_task_runner.py:60} INFO - Started process 4614 to run task
[2024-03-17T04:51:04.672+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'study_case_etl_cloud_storage_dua', 'format_to_parquet_task', 'manual__2024-03-17T04:50:55.736040+00:00', '--job-id', '903', '--raw', '--subdir', 'DAGS_FOLDER/etl_day_bigquery/study_case_etl_cloud_storage_dua.py', '--cfg-path', '/tmp/tmpfgquw7ar']
[2024-03-17T04:51:04.675+0000] {standard_task_runner.py:88} INFO - Job 903: Subtask format_to_parquet_task
[2024-03-17T04:51:04.712+0000] {task_command.py:423} INFO - Running <TaskInstance: study_case_etl_cloud_storage_dua.format_to_parquet_task manual__2024-03-17T04:50:55.736040+00:00 [running]> on host 1d5b76b26ba5
[2024-03-17T04:51:04.774+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Agus mahari' AIRFLOW_CTX_DAG_ID='study_case_etl_cloud_storage_dua' AIRFLOW_CTX_TASK_ID='format_to_parquet_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-17T04:50:55.736040+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-17T04:50:55.736040+00:00'
[2024-03-17T04:51:04.776+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/csv_to_parquet.py", line 6, in format_to_parquet
    if not src_file.endswith('.csv'):
AttributeError: 'list' object has no attribute 'endswith'
[2024-03-17T04:51:04.782+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=study_case_etl_cloud_storage_dua, task_id=format_to_parquet_task, execution_date=20240317T045055, start_date=20240317T045104, end_date=20240317T045104
[2024-03-17T04:51:04.791+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 903 for task format_to_parquet_task ('list' object has no attribute 'endswith'; 4614)
[2024-03-17T04:51:04.809+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-17T04:51:04.828+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
