[2024-03-16T14:24:33.366+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: study_case_etl_cloud_storage.bigquery_external_table_task manual__2024-03-16T14:24:22.457937+00:00 [queued]>
[2024-03-16T14:24:33.378+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: study_case_etl_cloud_storage.bigquery_external_table_task manual__2024-03-16T14:24:22.457937+00:00 [queued]>
[2024-03-16T14:24:33.378+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-16T14:24:33.393+0000] {taskinstance.py:2214} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2024-03-16 14:24:22.457937+00:00
[2024-03-16T14:24:33.399+0000] {standard_task_runner.py:60} INFO - Started process 6445 to run task
[2024-03-16T14:24:33.403+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'study_case_etl_cloud_storage', 'bigquery_external_table_task', 'manual__2024-03-16T14:24:22.457937+00:00', '--job-id', '742', '--raw', '--subdir', 'DAGS_FOLDER/etl_day_bigquery/study_case_etl_cloud_storage.py', '--cfg-path', '/tmp/tmpbdjnk2v4']
[2024-03-16T14:24:33.406+0000] {standard_task_runner.py:88} INFO - Job 742: Subtask bigquery_external_table_task
[2024-03-16T14:24:33.454+0000] {task_command.py:423} INFO - Running <TaskInstance: study_case_etl_cloud_storage.bigquery_external_table_task manual__2024-03-16T14:24:22.457937+00:00 [running]> on host 1d5b76b26ba5
[2024-03-16T14:24:33.545+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Agus mahari' AIRFLOW_CTX_DAG_ID='study_case_etl_cloud_storage' AIRFLOW_CTX_TASK_ID='bigquery_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-16T14:24:22.457937+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-16T14:24:22.457937+00:00'
[2024-03-16T14:24:33.548+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-03-16T14:24:33.549+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-16T14:24:33.550+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-03-16T14:24:38.410+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1780, in execute
    table = bq_hook.create_empty_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 485, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 421, in create_empty_table
    return self.get_client(project_id=project_id, location=location).create_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 793, in create_table
    api_response = self._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 827, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/forward-entity-411314/datasets/agusmahari_data_lake/tables?prettyPrint=false: Error while reading table: raw-webtoon-insight, error message: Input file is not in Parquet format. File: gs://agusmahari_data_lake/raw/webtoon_insight/scrape_webtoon_officials_2024-03-16.parquet
[2024-03-16T14:24:38.419+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=study_case_etl_cloud_storage, task_id=bigquery_external_table_task, execution_date=20240316T142422, start_date=20240316T142433, end_date=20240316T142438
[2024-03-16T14:24:38.433+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 742 for task bigquery_external_table_task (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/forward-entity-411314/datasets/agusmahari_data_lake/tables?prettyPrint=false: Error while reading table: raw-webtoon-insight, error message: Input file is not in Parquet format. File: gs://agusmahari_data_lake/raw/webtoon_insight/scrape_webtoon_officials_2024-03-16.parquet; 6445)
[2024-03-16T14:24:38.447+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-16T14:24:38.465+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
