[2024-03-16T07:51:52.508+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: study_case_etl_cloud_storage.create_external_table_task manual__2024-03-16T07:46:36.238460+00:00 [queued]>
[2024-03-16T07:51:52.515+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: study_case_etl_cloud_storage.create_external_table_task manual__2024-03-16T07:46:36.238460+00:00 [queued]>
[2024-03-16T07:51:52.515+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-03-16T07:51:52.525+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_external_table_task> on 2024-03-16 07:46:36.238460+00:00
[2024-03-16T07:51:52.530+0000] {standard_task_runner.py:60} INFO - Started process 383 to run task
[2024-03-16T07:51:52.534+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'study_case_etl_cloud_storage', 'create_external_table_task', 'manual__2024-03-16T07:46:36.238460+00:00', '--job-id', '678', '--raw', '--subdir', 'DAGS_FOLDER/etl_day_bigquery/study_case_etl_cloud_storage.py', '--cfg-path', '/tmp/tmp3jlhiy9d']
[2024-03-16T07:51:52.536+0000] {standard_task_runner.py:88} INFO - Job 678: Subtask create_external_table_task
[2024-03-16T07:51:52.572+0000] {task_command.py:423} INFO - Running <TaskInstance: study_case_etl_cloud_storage.create_external_table_task manual__2024-03-16T07:46:36.238460+00:00 [running]> on host 1d5b76b26ba5
[2024-03-16T07:51:52.632+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Agus mahari' AIRFLOW_CTX_DAG_ID='study_case_etl_cloud_storage' AIRFLOW_CTX_TASK_ID='create_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-16T07:46:36.238460+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-16T07:46:36.238460+00:00'
[2024-03-16T07:51:52.635+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-03-16T07:51:52.635+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-16T07:51:52.636+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-03-16T07:51:57.535+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_day_bigquery/study_case_etl_cloud_storage.py", line 110, in create_external_table
    external_table_task.execute(context=kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1780, in execute
    table = bq_hook.create_empty_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 485, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 421, in create_empty_table
    return self.get_client(project_id=project_id, location=location).create_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 793, in create_table
    api_response = self._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 827, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/forward-entity-411314/datasets/agusmahari_data_lake/tables?prettyPrint=false: Error while reading table: raw-webtoon-insight, error message: Input file is not in Parquet format. File: gs://agusmahari_data_lake/raw/webtoon_insight/scrape_webtoon_officials_2024-03-16.parquet
[2024-03-16T07:51:57.545+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=study_case_etl_cloud_storage, task_id=create_external_table_task, execution_date=20240316T074636, start_date=20240316T075152, end_date=20240316T075157
[2024-03-16T07:51:57.559+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 678 for task create_external_table_task (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/forward-entity-411314/datasets/agusmahari_data_lake/tables?prettyPrint=false: Error while reading table: raw-webtoon-insight, error message: Input file is not in Parquet format. File: gs://agusmahari_data_lake/raw/webtoon_insight/scrape_webtoon_officials_2024-03-16.parquet; 383)
[2024-03-16T07:51:57.573+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-16T07:51:57.585+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
