[2024-03-16T07:30:22.596+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: study_case_etl_cloud_storage.fetch_data_task manual__2024-03-16T07:19:12.706937+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-03-16T07:30:22.599+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
