[2024-03-12T20:08:34.573+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_delapan.fetch_data_task manual__2024-03-12T20:08:33.459607+00:00 [queued]>
[2024-03-12T20:08:34.581+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_delapan.fetch_data_task manual__2024-03-12T20:08:33.459607+00:00 [queued]>
[2024-03-12T20:08:34.581+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-12T20:08:34.591+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): fetch_data_task> on 2024-03-12 20:08:33.459607+00:00
[2024-03-12T20:08:34.596+0000] {standard_task_runner.py:60} INFO - Started process 109 to run task
[2024-03-12T20:08:34.599+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'example_delapan', 'fetch_data_task', 'manual__2024-03-12T20:08:33.459607+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/other_ingestion_postgre/main_dag_sql_delapan.py', '--cfg-path', '/tmp/tmpwtnjpztv']
[2024-03-12T20:08:34.601+0000] {standard_task_runner.py:88} INFO - Job 131: Subtask fetch_data_task
[2024-03-12T20:08:34.636+0000] {task_command.py:423} INFO - Running <TaskInstance: example_delapan.fetch_data_task manual__2024-03-12T20:08:33.459607+00:00 [running]> on host 44cfed336f7f
[2024-03-12T20:08:34.697+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_delapan' AIRFLOW_CTX_TASK_ID='fetch_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T20:08:33.459607+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-12T20:08:33.459607+00:00'
[2024-03-12T20:08:34.698+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-03-12T20:08:34.705+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/other_ingestion_postgre/main_dag_sql_delapan.py", line 31, in fetch_data
    engine = get_mysql_connection()
  File "/opt/airflow/dags/utils/mysqlconnection.py", line 23, in get_mysql_connection
    engine = create_engine(database_url, echo=True)
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 514, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 738, in make_url
    return _parse_url(name_or_url)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 794, in _parse_url
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: 'None'
[2024-03-12T20:08:34.712+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=example_delapan, task_id=fetch_data_task, execution_date=20240312T200833, start_date=20240312T200834, end_date=20240312T200834
[2024-03-12T20:08:34.721+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 131 for task fetch_data_task (invalid literal for int() with base 10: 'None'; 109)
[2024-03-12T20:08:34.734+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-12T20:08:34.755+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
