[2024-03-23T05:40:00.285+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/other_ingestion_postgre/main_dag.py
[2024-03-23T05:40:00.289+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/other_ingestion_postgre/main_dag.py for tasks to queue
[2024-03-23T05:40:00.302+0000] {logging_mixin.py:188} INFO - [2024-03-23T05:40:00.299+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/other_ingestion_postgre/main_dag.py
[2024-03-23T05:40:00.370+0000] {logging_mixin.py:188} INFO - [2024-03-23T05:40:00.355+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/other_ingestion_postgre/main_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/other_ingestion_postgre/main_dag.py", line 9, in <module>
    from postgres_connection import get_postgres_connection
ModuleNotFoundError: No module named 'postgres_connection'
[2024-03-23T05:40:00.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/other_ingestion_postgre/main_dag.py
[2024-03-23T05:40:00.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/other_ingestion_postgre/main_dag.py took 0.181 seconds
