[2024-03-30T16:20:08.641+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: study_case_etl_all_pipeline.bash_task_1 manual__2024-03-30T16:19:30.888515+00:00 [queued]>
[2024-03-30T16:20:08.654+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: study_case_etl_all_pipeline.bash_task_1 manual__2024-03-30T16:19:30.888515+00:00 [queued]>
[2024-03-30T16:20:08.655+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T16:20:08.671+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): bash_task_1> on 2024-03-30 16:19:30.888515+00:00
[2024-03-30T16:20:08.677+0000] {standard_task_runner.py:60} INFO - Started process 7207 to run task
[2024-03-30T16:20:08.681+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'study_case_etl_all_pipeline', 'bash_task_1', 'manual__2024-03-30T16:19:30.888515+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/running_dbt_core/study_case_etl_all_pipeline.py', '--cfg-path', '/tmp/tmpg7zvimiq']
[2024-03-30T16:20:08.684+0000] {standard_task_runner.py:88} INFO - Job 70: Subtask bash_task_1
[2024-03-30T16:20:08.727+0000] {task_command.py:423} INFO - Running <TaskInstance: study_case_etl_all_pipeline.bash_task_1 manual__2024-03-30T16:19:30.888515+00:00 [running]> on host 8e1e687a7cdb
[2024-03-30T16:20:08.795+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Agus mahari' AIRFLOW_CTX_DAG_ID='study_case_etl_all_pipeline' AIRFLOW_CTX_TASK_ID='bash_task_1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T16:19:30.888515+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-30T16:19:30.888515+00:00'
[2024-03-30T16:20:08.798+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-30T16:20:08.799+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt/credit_card_dwh && dbt deps && dbt seed --profiles-dir .']
[2024-03-30T16:20:08.809+0000] {subprocess.py:86} INFO - Output:
[2024-03-30T16:20:11.183+0000] {subprocess.py:93} INFO - [0m16:20:11  Running with dbt=1.7.11
[2024-03-30T16:20:14.124+0000] {subprocess.py:93} INFO - [0m16:20:14  Installing dbt-labs/dbt_utils
[2024-03-30T16:20:20.007+0000] {subprocess.py:93} INFO - [0m16:20:20  Installed from version 0.8.0
[2024-03-30T16:20:20.008+0000] {subprocess.py:93} INFO - [0m16:20:20  Updated version available: 1.1.1
[2024-03-30T16:20:20.011+0000] {subprocess.py:93} INFO - [0m16:20:20  Installing calogica/dbt_expectations
[2024-03-30T16:20:27.844+0000] {subprocess.py:93} INFO - [0m16:20:27  Installed from version 0.10.3
[2024-03-30T16:20:27.846+0000] {subprocess.py:93} INFO - [0m16:20:27  Up to date!
[2024-03-30T16:20:27.848+0000] {subprocess.py:93} INFO - [0m16:20:27  Installing calogica/dbt_date
[2024-03-30T16:20:28.595+0000] {subprocess.py:93} INFO - [0m16:20:28  Installed from version 0.10.0
[2024-03-30T16:20:28.597+0000] {subprocess.py:93} INFO - [0m16:20:28  Up to date!
[2024-03-30T16:20:28.599+0000] {subprocess.py:93} INFO - [0m16:20:28
[2024-03-30T16:20:28.600+0000] {subprocess.py:93} INFO - [0m16:20:28  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-03-30T16:20:28.601+0000] {subprocess.py:93} INFO - Update your versions in packages.yml, then run dbt deps
[2024-03-30T16:20:33.778+0000] {subprocess.py:93} INFO - [0m16:20:33  Running with dbt=1.7.11
[2024-03-30T16:20:34.793+0000] {subprocess.py:93} INFO - [0m16:20:34  Registered adapter: bigquery=1.7.7
[2024-03-30T16:20:34.853+0000] {subprocess.py:93} INFO - [0m16:20:34  Unable to do partial parsing because of a version mismatch
[2024-03-30T16:20:37.128+0000] {subprocess.py:93} INFO - [0m16:20:37  [[33mWARNING[0m]: Found patch for macro "decode_EDUCATION" which was not found
[2024-03-30T16:20:37.130+0000] {subprocess.py:93} INFO - [0m16:20:37  [[33mWARNING[0m]: Found patch for macro "decode_HOUSING" which was not found
[2024-03-30T16:20:37.133+0000] {subprocess.py:93} INFO - [0m16:20:37  [[33mWARNING[0m]: Found patch for macro "decode_INCOME" which was not found
[2024-03-30T16:20:37.135+0000] {subprocess.py:93} INFO - [0m16:20:37  [[33mWARNING[0m]: Found patch for macro "decode_JOB" which was not found
[2024-03-30T16:20:37.138+0000] {subprocess.py:93} INFO - [0m16:20:37  [[33mWARNING[0m]: Found patch for macro "decode_MARITAL" which was not found
[2024-03-30T16:20:37.139+0000] {subprocess.py:93} INFO - [0m16:20:37  Encountered an error:
[2024-03-30T16:20:37.140+0000] {subprocess.py:93} INFO - Compilation Error
[2024-03-30T16:20:37.140+0000] {subprocess.py:93} INFO -   Model 'model.credit_card_dwh.stg__credit_card' (models/staging/stg__credit_card.sql) depends on a source named 'final_project.raw_credit_card' which was not found
[2024-03-30T16:20:39.190+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-03-30T16:20:39.209+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-03-30T16:20:39.216+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=study_case_etl_all_pipeline, task_id=bash_task_1, execution_date=20240330T161930, start_date=20240330T162008, end_date=20240330T162039
[2024-03-30T16:20:39.236+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 70 for task bash_task_1 (Bash command failed. The command returned a non-zero exit code 2.; 7207)
[2024-03-30T16:20:39.278+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-30T16:20:39.301+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
